const letterAndMorse = [
    {Letter: "A", MorseCode: ".-"},
    {Letter: "B", MorseCode: "-..."},
    {Letter: "C", MorseCode: "-.-."},
    {Letter: "D", MorseCode: "-.."},
    {Letter: "E", MorseCode: "."},
    {Letter: "F", MorseCode: "..-."},
    {Letter: "G", MorseCode: "--."},
    {Letter: "H", MorseCode: "...."},
    {Letter: "I", MorseCode: ".."},
    {Letter: "J", MorseCode: ".---"},
    {Letter: "K", MorseCode: "-.-"},
    {Letter: "L", MorseCode: ".-.."},
    {Letter: "M", MorseCode: "--"},
    {Letter: "N", MorseCode: "-."},
    {Letter: "O", MorseCode: "---"},
    {Letter: "P", MorseCode: ".--."},
    {Letter: "Q", MorseCode: "--.-"},
    {Letter: "R", MorseCode: ".-."},
    {Letter: "S", MorseCode: "..."},
    {Letter: "T", MorseCode: "-"},
    {Letter: "U", MorseCode: "..-"},
    {Letter: "V", MorseCode: "...-"},
    {Letter: "W", MorseCode: ".--"},
    {Letter: "X", MorseCode: "-..-"},
    {Letter: "Y", MorseCode: "-.--"},
    {Letter: "Z", MorseCode: "--.."},

    //numbers
    {Letter: "0", MorseCode: "-----"},
    {Letter: "1", MorseCode: ".----"},
    {Letter: "2", MorseCode: "..---"},
    {Letter: "3", MorseCode: "...--"},
    {Letter: "4", MorseCode: "....-"},
    {Letter: "5", MorseCode: "....."},
    {Letter: "6", MorseCode: "-...."},
    {Letter: "7", MorseCode: "--..."},
    {Letter: "8", MorseCode: "---.."},
    {Letter: "9", MorseCode: "----."},

    //characters
    {Letter: ".", MorseCode: ".-.-.-"},
    {Letter: ",", MorseCode: "--..--"},
    {Letter: "?", MorseCode: "..--.."},
    {Letter: "'", MorseCode: ".----."},
    {Letter: "!", MorseCode: "-.-.--"},
    {Letter: "/", MorseCode: "-..-."},
    {Letter: "(", MorseCode: "-.--."},
    {Letter: ")", MorseCode: "-.--.-"},
    {Letter: "&", MorseCode: ".-..."},
    {Letter: ":", MorseCode: "---..."},
    {Letter: ";", MorseCode: "-.-.-."},
    {Letter: "=", MorseCode: "-...-"},
    {Letter: "+", MorseCode: ".-.-."},
    {Letter: "-", MorseCode: "-....-"},
    {Letter: "_", MorseCode: "..--.-"},
    {Letter: "\"", MorseCode: ".-..-."},
    {Letter: "$", MorseCode: "...-..-"},
    {Letter: "@", MorseCode: ".--.-."},

];

export default letterAndMorse